Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 12
  Exclude:
    - spec/dummy/db/migrate/*.rb
    - app/forms/tramway/core/extendable_forms_helpers/class_builder.rb
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 18
  Exclude:
    - spec/dummy/db/migrate/*.rb
    - app/forms/tramway/core/extendable_forms_helpers/class_builder.rb
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - spec/dummy/config/application.rb
    - lib/tramway/core/version.rb
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Style/MixinUsage:
  Exclude:
    - bin/*
    - spec/dummy/bin/*
Metrics/PerceivedComplexity:
  Max: 10
Style/ClassVars:
  Exclude:
    - app/forms/tramway/core/extended_application_form.rb
    - app/forms/tramway/core/application_form.rb
    - app/decorators/tramway/core/associations/class_helper.rb
Naming/MethodParameterName:
  Exclude:
    - app/decorators/tramway/core/associations/class_helper.rb
AllCops:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/seeds.rb
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - spec/dummy/Rakefile
  TargetRubyVersion: 2.7
