name: Ruby

on: [push]

postgres:
  image: postgres:latest
  ports:
  - 5432:5432

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-versions: 2.6.5, 2.7.0, 2.5.7, 2.4.9
    - name: Build and test with Rake
      run: |
        gem install bundler -v '2.1.2'
        bundle install --jobs 4 --retry 3
        bundle exec rspec
        rubocop
        
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
