name: Ruby

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-versions: 2.6.5, 2.7.0, 2.5.7, 2.4.9
    - name: Clone current repo
      uses: actions/checkout@master
      with:
        repository: purple-magic/tramway-core
    - name: Clone dummy repo
      uses: actions/checkout@master
      with:
        repository: purple-magic/tramway_test
        path: spec/dummy
    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Build and test with Rake
      run: |
        gem install bundler -v '2.1.2'
        echo $(ls)
        bundle install
        bundle exec rubocop
        
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
