name: Tests

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['2.3', '2.4', '2.5', '2.6', '2.7']
    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: runner

    run-on: ${{ matrix.os }}
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.6
        bundler-cache: true

    - name: Clone current repo
      uses: actions/checkout@master
      with:
        repository: purple-magic/tramway-core

    - name: Clone dummy repo
      uses: actions/checkout@master
      with:
        repository: purple-magic/tramway_test
        branch: develop
        path: spec/dummy
    
    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Bundle
      run: |
        gem install bundler -v '2.1.2'
        bundle install --jobs 4 --retry 3
      
    - name: Setup Database
      run: |
        cp spec/dummy/config/database.yml.github-actions spec/dummy/config/database.yml
        cd spec/dummy && bundle exec rails db:create db:migrate
      env:
        RAILS_ENV: test
        POSTGRES_USER: runner

    - name: Tests
      run: |
        rake
